### ISSUE TITLE
arnold 5.2.2.0 complie faild

### ISSUE THREAD

**Issue by xtvjxk123456** [iamsleepy/ApiMeshShapeArnoldTranslator#1]
arnold 5.2.2.0
maya 2017
vs2012

`1>  Creating library C:\Users\Administrator\Desktop\ApiMeshShapeArnoldTranslator\x64\Release\ArnoldTranslator.lib and object C:\Users\Administrator\Desktop\ApiMeshShapeArnoldTranslator\x64\Release\ArnoldTranslator.exp
1>apiMeshShapeTranslator.obj : error LNK2001: unresolved external symbol "public: class apiMeshGeom * __cdecl apiMesh::meshGeom(void)" (?meshGeom@apiMesh@@QEAAPEAVapiMeshGeom@@XZ)
1>C:\Users\Administrator\Desktop\ApiMeshShapeArnoldTranslator\x64\Release\ArnoldTranslator.dll : fatal error LNK1120: 1 unresolved externals
1>已完成生成项目“ArnoldTranslator.vcxproj”的操作 - 失败。
`

complie faild. can not  figure out why.
can you help please?

**Comment by iamsleepy** [comment]
This link error suggests that apiMeshGeom symbol haven't been found. When I was writing the sample, I modified apiMeshShape and exported the apiMeshGeom. It is required when linking to the translator.

```
    //Modify apiMeshGeom* meshGeom(); in the apiMeshShape.h
    __declspec(dllexport) apiMeshGeom*     __cdecl meshGeom();
```

I've added these instructions to the Readme.MD and link to my original blog.

**Comment by xtvjxk123456** [comment]
thanks,
Can you explain more about "export "section?

**Comment by iamsleepy** [comment]
Export means it exports this class in its library and could be linked in another module. In this case, the translator needs to get geometry data from apiMeshShape. So I exported meshGeom function in apiMeshShape to allow it to be linked with translator and called from the translator.

**Comment by xtvjxk123456** [comment]
thank you very much！

**Comment by xtvjxk123456** [comment]
sorry,i found you already modified the source code ,but still failed to build it.
![image](https://user-images.githubusercontent.com/8720281/56740064-bfb23180-67a2-11e9-9921-1c6d791ec68c.png)

![image](https://user-images.githubusercontent.com/8720281/56740127-e4a6a480-67a2-11e9-9438-68db3113a26a.png)

**Comment by xtvjxk123456** [comment]
vs2017 
toolset v110
arnold 5.2.2.0

**Comment by iamsleepy** [comment]
Have you added it in apiMeshShape solution and rebuilt it? It's not only for translator to import it, the key here is to rebuild apiMeshShape sample in the devkit with updated header and link to the library it generated.

**Comment by xtvjxk123456** [comment]
What you said is true, it is my problem. it works and thank you very much!
