### ISSUE TITLE
need help about extension 

### ISSUE THREAD

**Issue by xtvjxk123456** [iamsleepy/ApiMeshShapeArnoldTranslator#2]
sorry to disturb you.
I need some help with extension
I wrote a custom node, which is a texture/2d node. How do I make it render by arnold? 
I found some information on the Internet and tried some things, but it didn't work.
I found that CNodeTranslator::AddArnoldNode needs the type parameter. What does this mean?
a node already in arnold ?or something?

**Comment by iamsleepy** [comment]
Hi,

Have you read this document?

https://docs.arnoldrenderer.com/display/A5AFMUG/Creating+an+Arnold+Shader+for+Maya

If you want to write an extension

https://docs.arnoldrenderer.com/display/A5AFMUG/Creating+a+basic+extension

is a tutorial for phong shading. For AddArnoldNode, it will tell Arnold which kind of current extension is. For the sample in this repo, it is a polymesh; for the sample on Arnold's website, it is standard_surface

Yours,
Li

**Comment by xtvjxk123456** [comment]
thanks for your reply
